spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/homework?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: root
  #Redis configurations
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
        timeout: 0
